### ISSUE TITLE
Don't Panic To-Do

### ISSUE THREAD

**Issue by linsydeanna** [linsydeanna/dont-panic#1]
- [ ] Rename incident to currentIncident
- [ ] Delete a report
- [ ] Add graphs for reports
- [ ] Add post-incident questions
- [x] Add breathing animation
- [ ] Add 2-4 other tracks based on symptoms
- [ ] Style for mobile
- [ ] Style for tablet
- [ ] Fix alerts
- [ ] Landing page
- [ ] Fix CSS transition flash between components
- [ ] Integrate Fitbit?
- [ ] Organize attacks and Fitbit history into graphs
- [ ]  Add option for remembering password
- [ ] Connect to firebase
- [ ] Logo
- [ ] Add custom symptoms
- [ ] Add custom 
- [ ] Add quote animations between components
- [ ] Add time range for reports
- [ ] Connect routing to redux
- [ ] Check for symptoms duplicates

**Comment by nellarro** [comment]
Is this open for PRs @linsydeanna?
